name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Stub secrets
        run: cp sample.env .env
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true
      - name: Detekt
        run: ./gradlew detekt lintKotlin --continue
      - name: Upload build reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: detekt
          path: |
            app/build/reports/detekt/detekt.html
            data/build/reports/detekt/detekt.html
            domain/build/reports/detekt/detekt.html
