name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Stub secrets
        run: cp sample.env .env
      - name: Check Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Detekt
        uses: gradle/gradle-build-action@v2
        with:
          arguments: detekt
      - name: Upload build reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: detekt
          path: |
            app/build/reports/detekt/detekt.html
            data/build/reports/detekt/detekt.html
            domain/build/reports/detekt/detekt.html
